// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDo.Model;

#nullable disable

namespace ToDo.Migrations
{
    [DbContext(typeof(ToDoDbContext))]
    partial class ToDoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ToDo.Model.Category", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = "1",
                            Name = "Work"
                        },
                        new
                        {
                            ID = "2",
                            Name = "Family"
                        },
                        new
                        {
                            ID = "3",
                            Name = "Birth"
                        },
                        new
                        {
                            ID = "4",
                            Name = "Fun"
                        },
                        new
                        {
                            ID = "5",
                            Name = "Sport"
                        },
                        new
                        {
                            ID = "6",
                            Name = "Study"
                        });
                });

            modelBuilder.Entity("ToDo.Model.ToDo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            CategoryId = "1",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Hello,I would like to take out something",
                            Status = 0,
                            Title = "Special"
                        },
                        new
                        {
                            Id = "2",
                            CategoryId = "2",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Qingming Festival holiday home",
                            Status = 0,
                            Title = "Go Home"
                        },
                        new
                        {
                            Id = "3",
                            CategoryId = "3",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Remember to buy gift home",
                            Status = 0,
                            Title = "Girlfriend's Birthday"
                        },
                        new
                        {
                            Id = "4",
                            CategoryId = "2",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Remember to pack your luggage",
                            Status = 0,
                            Title = "Japan Tourism"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
